### ISSUE TITLE
Cannot compile with nightly 1.38

### ISSUE THREAD

**Issue by ethanfrey** [japaric/serde-json-core#15]
I was trying to convert from serde-json to serde-json-core to get smaller sizes on my wasm code. I was also happy not to pull in any floating support, as I only want ints. However, I got the following error (about 50 times) when compiling:

```
error[E0277]: the trait bound `ser::Error: serde::de::StdError` is not satisfied
   --> /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-json-core-0.0.1/src/ser/mod.rs:121:13
    |
121 | impl<'a, B> ser::Serializer for &'a mut Serializer<B>
    |             ^^^^^^^^^^^^^^^ the trait `serde::de::StdError` is not implemented for `ser::Error`

error[E0277]: the trait bound `ser::Error: serde::de::StdError` is not satisfied
   --> /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-json-core-0.0.1/src/ser/mod.rs:339:6
    |
339 | impl ser::Error for Error {
    |      ^^^^^^^^^^ the trait `serde::de::StdError` is not implemented for `ser::Error`
```

I was pulling the `0.0.1` crate which seems to be the only one published. Any tips?

**Comment by japaric** [comment]
Fixed in #20
